version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.23
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - ${ES_PORT}:${ES_PORT}
    networks:
      - docker-elk
  web-service:
    build: .
    container_name: app
    environment:
      - ES_HOST=${ES_HOST}
      - ES_PORT=${ES_PORT}
      - ES_INDEX=${ES_INDEX}
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - docker-elk
networks:
  docker-elk:
    driver: bridge
